"""add colume to user

Revision ID: 99b1767163fb
Revises: 14d8701586ea
Create Date: 2016-11-12 23:27:17.010102

"""

# revision identifiers, used by Alembic.
revision = '99b1767163fb'
down_revision = '14d8701586ea'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirmed')
    ### end Alembic commands ###
